### ISSUE TITLE
Getting a sample of tokens

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#11]
In the example in the tutorial, tokvecs has less than a thousand rows, but in the corpus I am testing I get eleven thousand tokens. That would lead to a huge cosine similarity matrix. Would it be possible to extract a random sample of rows from tokvecs to create that matrix?

**Comment by enzocxt** [comment]
There is currently no such method for extracting a random sample of rows. But of course it is possible. Implementation of this kind of method may cost many hours. So I can not provide you immediately. And could you explain to some extent, theoretical reasons of doing this to make me better understand.  
By now, there is a method `select_submatrix(type_str)` for TVMatrix. You could provide a type item (e.g. _solution/NN0_) for the method to get a submatrix which only contains rows of tokens of this type item.  
```python
>>> tokvecs = TokVecManager.make_token_vector(soccMatrix, tcWeightMatrix)
>>> print(tokvecs)
[583, 9022]            that/DTQ  what/PNQ  no/DT0   &amp;/CJC  its/PNP  say/VVD   than/CJS  ...
solution/NN2/J80/678   -0.0962   -0.5935   0.0900   -2.3797    0.5435   -3.7761   -0.0011   ...
solution/NN2/J51/1966  0.2709    8.0326    5.9926   -3.1560    3.9806   5.4539    0.3023    ...
solution/NN2/J51/1744  0.6498    5.3414    0.7543   -4.9080    0.6615   -0.7691   4.4335    ...
solution/NN2/J47/422   4.0098    2.3131    5.7155   -11.4648   10.5834  -1.6618   9.0430    ...
solution/NN2/J37/1566  8.6211    -6.7166   -1.5732  -18.4878   -7.2626  -9.7474   2.0551    ...
solution/NN2/J18/2246  -1.7134   -8.1618   -0.6829  21.8770    -1.6261  -11.8806  -1.1070   ...
solution/NN2/J18/2216  -1.7514   -7.6265   -1.3971  22.7329    -1.2255  -11.8139  -1.7750   ...
...                    ...       ...       ...      ...        ...      ...       ...       ...
>>> subvecs = tokvecs.select_submatrix('solution/NN0')
>>> print(subvecs)
[58, 9022]             that/DTQ  what/PNQ  no/DT0   &amp;/CJC  its/PNP  say/VVD  than/CJS  ...
solution/NN0/A09/2220  1.5969    0.6395    8.2352   -5.0819    1.1489   -1.0508  3.3156    ...
solution/NN0/A30/1195  0.2154    0.4371    0.4429   -1.2537    -0.9037  1.5433   0.4551    ...
solution/NN0/B03/1353  8.8409    -0.4195   9.2094   0.1102     -1.6935  -2.0926  4.7868    ...
solution/NN0/B03/932   -0.0249   8.1376    10.2427  -6.4859    -0.5884  1.9562   0.1956    ...
solution/NN0/B15/2140  2.9970    5.4541    4.4826   -6.8984    5.3772   -2.7299  8.1057    ...
solution/NN0/B15/36    -1.3707   2.3147    3.5130   -1.1991    3.2601   -0.5690  3.7656    ...
solution/NN0/B19/2153  4.6116    1.3408    0.6491   1.1358     2.0936   -0.8698  -0.3787   ...
...                    ...       ...       ...      ...        ...      ...      ...       ...
```
Hope this method would help.

**Comment by delhikiev** [comment]
Thank you. There was no theoretical reason for this, just a practical one. I thought the cosine similarity at the token level was taking a lot of time because it had almost twelve thousand rows, but that's not the case. The problem is somewhere else, and computing such a big cosine similarity matrix does not take long at all.

**Comment by enzocxt** [comment]
I've just implemented a sampling method for TVMatrix. You can try it.  
Time cost problems appear more frequently in saving matrices when matrices are very large then the calculation of matrices such as cosine similarity matrix. Since in the model we normally use methods provided by sklearn (or other packages, e.g. numpy) to calculate matrices of measures.  
And as we use json format to save sparse matrices such as _xxx.wcmx.pmi.json_, and use inherent format and method to save square matrices (as numpy.ndarray), sparse matrices' saving costs much more time than square matrices. So if you encountered time cost problem, try first with sparse matrices saving parts in the model.  
You can also post the location where the problem raises and the reason you found, to help me locate the bottle neck of the efficiency of our model. Thanks :-)

**Comment by delhikiev** [comment]
Excellent, thank you! As you say, the size of the matrix doesn't make such a difference in how long it takes to generate the cosine similarity matrix (although it took me almost 13 minutes with 11888 rows, and 8 seconds with a 1188), but it does matter when saving it. In that sense, sampling the token vectors is very useful. I already added the instructions in 'Suggestions for the tutorial' in the wiki.

The reason I thought it took a lot of time was that compute_cosine wasn't working with tokvecs before and it took at least 20 minutes to decide it wouldn't work, but now that it does, it's not such a problem.
