### ISSUE TITLE
Type Weight Matrix

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#12]
I was wondering if it would be useful (and possible) to get a sliced version of the SOCC matrix, with only the pertinent type as rows, for the TypeWeight matrix, instead of one just as huge. It might be lighter and faster.

**Comment by enzocxt** [comment]
Let me try to understand your suggestion by describing our procedures.  
In the _making token vectors_ procedure, we first make a __token weight matrix__ based on __token-context boolean matrix__ and __type weight matrix__. The row dimension of the type weight matrix should be the same as the column dimension of the token-context boolean matrix.  
Suppose now we only calculate the vector for one token. After we've computed the collocate information of this token and the target types, we can get a boolean vector of dimension __m__, which is the number of our targets words/types. Then for the token we want to calculate, we select the corresponding column (same type of the token) of the type weight matrix (m X n). By this token boolean vector and type weight vector, we can get the token weight vector who has the dimension __m__. Then based on this vector and the SOCC matrix (m X k), we can get the final token vector with dimension __k__.   
Now, assume we have a SOCC matrix with dimension __M__ X __k__, and we calculate the token by context words cooccurrence boolean vector based on __m__ context word types. All context word types belongs to the target words of SOCC matrix. Your suggestion is that select a __m__ X __k__ sliced SOCC matrix for our calculation? Am I understanding correctly?

**Comment by delhikiev** [comment]
Mmm no. Sorry, I didn't explain myself clearly.
In the tutorial, the **typeweight matrix** before transposing is exactly the same as the SOCC matrix. Number of columns of **token-context boolean matrix** equals number of rows in both **type weight matrix** and **SOCC matrix**, equals the target types, while the number of columns of **type weight matrix** and **SOCC matrix** are equal to each other. I know it's not necessarily the case, but that's the example given in the tutorial, because those are the pmi matrices we already have.
I was thinking that maybe for the **type weight matrix**, instead of using the same matrix as for **SOCC matrix**, it would be useful to used a sliced version with the same rows (target types) but only the columns of the types of the token vectors (not the target types). So instead of loading twice a 5000x10000 matrix, we load one of 5000x10000 and one of 5000x2 maybe.
I admit I don't know much about how cumbersome it is to deal with different sizes of matrices, so maybe it's more costly to slice the matrix than to use two large ones, but I thought it worth suggesting.

**Comment by enzocxt** [comment]
Yes, it is a good idea to slice the large type weight matrix for a specific research. I think we will have many repeatedly used type weight matrix, SOCC matrix, etc in future projects. These matrices would be very large and be sliced for different researches. So for token level, after we've decided our target tokens (so do the types), we slice the large type weight matrix which already exists somewhere on the server, and get a small one for making the token weight matrix.  
But loading this large type weight matrix in the current tutorial happens (in method make_tc_weight_matrix()) before loading SOCC matrix (in method make_token_vector()). So loading twice large matrices would not affects model efficiency. While it is certainly slow to load it twice.  
The matrix which has to interact with the large SOCC matrix, is the __token weight matrix__. This token weight matrix is possibly smaller than the type weight matrix, if you don't use too many target tokens. So I think the bottleneck may be here.  
Could you show me how large is your number of target tokens? I think we have to also slice these tokens to get sliced token weight matrices.

**Comment by delhikiev** [comment]
In my current project I have 11888 tokens. Thanks to the sample method you added the other day, we can get smaller matrices, but that's after interacting with SOCC matrix (and before the cosine similarity matrix). Slicing before the interaction with the SOCC matrix might be better than doing it afterwards. Still, it should be a random sample instead of a controlled slicing.

**Comment by enzocxt** [comment]
I just added a sampling method for TCMatrix. So this makes it possible to sample a token-context position matrix or a token weight matrix before the interaction with the SOCC matrix. You could try this later and check if it works. Thanks.

**Comment by delhikiev** [comment]
I get an AttributeError, that 'sample' doesn't exist for TCMatrix, and when I checked the Matrix.py script couldn't find any new method. Is it somewhere else? Or maybe a problem of the files updating?

**Comment by enzocxt** [comment]
Sorry, yes, there was a repository updating mistake. Try now please.

**Comment by delhikiev** [comment]
I see the changes on the script but I still get AttributeError, both for tcMTX (before the typeweight) and tcWeightMTX (after typeweight). I reappended the path for the modules and reimported TCMatrix, do I have to import something else?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-53-1f5ee49efa95> in <module>()
----> 1 tcSmall = tcWeightMTX.sample()

AttributeError: 'TCMatrix' object has no attribute 'sample'
```

**Comment by enzocxt** [comment]
I just used `hasattr(TCMatrix, 'sample')` to check if TCMatrix has attribute or method 'sample'. The result is 'True'. As mentioned, you reimported TCMatrix by `from typetoken.Matrix import TCMatrix`. Then the _sample_ method should be there. That's weird. Try reloading your tcWeightMTX from file. And then see if it has _sample_ method?

**Comment by delhikiev** [comment]
It works! :)

I tried loading the token-context-position matrix and the sampling worked perfectly there.
I also generated a typeweight matrix with the whole token-context-position matrix and the sampling worked perfectly there as well.

I had also shut down the kernel and restarted, I don't know if that had anything to do with it.
