### ISSUE TITLE
Can't generate cosine similarity matrix from token vectors

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#13]
`MatrixManager.compute_cosine` doesn't recognize tokvecs (result of `TokVecManager.make_token_vector(soccMTX, tcWeightMTX)`) as valid. Is there a step missing?
(In the image below the tokvecs is loaded from a file, but I get the same result when generating it on the spot)
It does work with tcWeightMTX, but that doesn't include second order co-occurrence information.

![image](https://user-images.githubusercontent.com/16564533/40240323-9ed91d7c-5ab8-11e8-9ee3-eb72157ef3a9.png)

**Comment by enzocxt** [comment]
This error appears because I forgot the tokvecs is an instance of TVMatrix. So now please try to load tokvecs by `TVMatrix.load(tokvecFile, fmt='pmi')`.

**Comment by delhikiev** [comment]
Yes, now it works! Thank you!
It works both loading the file and with the direct output of make_token_vector, much faster for the sample than for the whole tokvecs matrix.
