### ISSUE TITLE
Empty rows in cosine similarity matrix

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#14]
The cosine similarity matrix at token level has some empty rows. I checked the context of some of the corresponding tokens and they don't seem too strange.
They are from the COHA. E.g. 
nf_1964_774160_10055 -> . But both these are spurious **states**. The fear of God descends upon man without
nf_1963_774144_7083 -> to receive a kickback from the florist, and in some **states** he is barred by law from owning his own flower

In the sample matrix, with 1188 rows, 331 are all 0. What could be the reason?

**Comment by delhikiev** [comment]
I checked and in the make_token_context_position section those tokens are counted but no words from their context get any value. That is weird because at least 'fear', 'man' and 'law' should've been considered (they do get counted in other tokens). I think I could just ignore these rows for now but it looks like a proper bug.

**Comment by enzocxt** [comment]
This seems to be a weird and possibly complex bug. I will check and try to solve it, but you may need to wait for a while.

**Comment by delhikiev** [comment]
Yes. No problem, I always need to sample anyways so I can just ignore the problematic tokens for now.

**Comment by delhikiev** [comment]
I don't know if this information is really helpful, but just in case:

I created a new token vector matrix with the same type, the same corpus, but different set of target words (10 thousand instead of 5, and any kind of word instead of only lowercase nouns).

One result from this was that I got more tokens: 12031 instead of 11888. I suppose the extras are tokens that had no match for the previous target words but they do with the new words?
Secondly, there were still rows with only 0s (231 and 242 in each of two samples of 1203 tokens).

So my guess is that the selection of tokens works (it knows which tokens have a match in their context) but something slips when recovering the position.

Hope this helps (no rush yet, though)

**Comment by delhikiev** [comment]
I checked the information in a token-context-position matrix and it was not correct.
The path to the matrices is /home/mariana/COHA-II/
The file I showed you is COHA.state_country.sample1.tcmx.position.json and the token I checked is token number 1 (second token in the list): state/np1/nf_1964_773618/18853
The corpus file can be found in /home/semmetrix/nepho/COHA55-64 but in any case the file for that token is also in /home/mariana.
