### ISSUE TITLE
Multiplying matrices from different corpora

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#15]
I want to use a pmi matrix with data from one corpus (COHA) as SOCC matrix for a token matrix of another corpus (Semcor). So I will have to multiply a matrix of *n*x*m* (*n* vectors and *m* context features) and one of *m*x*k*.
I know *m* is the same length for both matrices and that the types are the same because I made sure of it. But the frequency dictionaries used to generate the matrices have different frequencies, so the 'order' is different. Is that a problem?
I mean, when multiplying, does `make_token_vector()` consider the order or the identity of the types?

**Comment by enzocxt** [comment]
Currently, no. The method `make_token_vector()` does not check this kind of information of the two input matrices. When the two input matrices are given to this method, it is assumed that the dimensions and the word lists and the order of the word lists are the same.  
I thought about reordering an existing matrix based on a given word sequence. The situation you mentioned would be solved by first checking the dimensions and word lists of the two input matrices, and then reordering one of them to make them consistent.  
This _check_ and _reorder_ procedure will be added to the method `make_token_vector()` later. As soon as it is there (hope it won't take too long), I will inform you here in this topic.

**Comment by delhikiev** [comment]
I tried `make_token_vector` with the same CollocDict for tcWeightMatrix.featureDict and soccMTX.wordDict and there was no problem. (`x.equal(y)` is true)
Now I'm trying with two different CollocDicts, with the same items but different frequencies, (`x.equal(y)` is false but `x.equal_items_list(y)` is true) and I get the following error:

```python
>>> tokvecs = TokVecManager.make_token_vector(soccMTX, tcWeightMTX)
KeyErrorTraceback (most recent call last)
<ipython-input-23-cefd9752e4d7> in <module>()
----> 1 tokvecs = TokVecManager.make_token_vector(soccMTX, tcWeightMTX)

/home/mariana/typetoken/Manager.pyc in make_token_vector(cls, soccMatrix, tcWeightMatrix, operation)
   1067                 # they have the same item list
   1068                 # but the frequency dicts are not the same
-> 1069                 right_mtx = soccMatrix.get_sync_matrix(tcWeightMatrix.item2colid)
   1070                 # soccMatrix.reorder(axis=0, item_list=tcWeightMatrix.colid2item)
   1071             else:

/home/mariana/typetoken/Matrix.pyc in get_sync_matrix(self, item2id, axis)
    937         for i in range(len(old_id2item)):
    938             item = old_id2item[i]
--> 939             new_id = new_item2id[item]
    940             new_indices.append(new_id)
    941         new_indices = np.array(new_indices)

KeyError: u'United'
```
1) manual application of equal_item_list confirms that both dictionaries have the same items
2) manual inspection of the dictionaries confirms that neither of them have an item called 'United', but they do have one called 'united', in lower case.
