### ISSUE TITLE
Other association measures

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#17]
Among the alternatives to pmi, we should give priority to positive pmi, it would be great to add it soon.

**Comment by delhikiev** [comment]
In my version of Manager.py, after line 83, I added

```python
 if pmi[i] < 0:
    pmi[i] = 0
```

to set all negative pmis to 0.
If there is a more elegant answer. it's welcome, but for now it seems to work.

**Comment by enzocxt** [comment]
It's fine to do this. And maybe a slightly better to change _0_ to _0.0_. (I just add this ppmi() method. Could you check it?)  
Sorry for not adding this so soon. I've been dealing with the #15. There are much more to do than I thought and then I forgot about this issue. If it is possible, would you add labels to represent the priorities of the issues.

**Comment by delhikiev** [comment]
The method works, thank you.
I did label this as 'enhancement' at first, because I wasn't aware of how much of a priority it was. Next time I will.
