### ISSUE TITLE
TypeError in compute_cosine(tokvecs)

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#22]
![image](https://user-images.githubusercontent.com/16564533/44041130-54da9ab2-9f1d-11e8-8423-e31ddbacaf65.png)

**Comment by enzocxt** [comment]
Hi Mariana,

Does the new ttmx work?

I just add a submatrix() method for tvmx.
    tvmx.submatrix(type_list=[’type1/NN0’, ’type2/NN2'])
You can provide a list of types to it, and then you will get a submatrix which contains only the tokens of these types.
But it is a very rough method. If you meet bugs or have advices, tell me to fix and improve.

Best,
Tao

**Comment by delhikiev** [comment]
Hi Tao,

I generated cosine similarity matrix at token level successfully, I could also save them and am about to look at them on R.

I will check the submatrix method this afternoon, thanks.

Best,
Mariana
