### ISSUE TITLE
cosine distance matrices saved as .npz instead of .npy

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#24]
I generated distance matrices for all my tokens and for either random samples or subsets of types, and saved them like this:
 ```python
ending = 'socc.cw.tvmx.dist.npy.pac'
s_fn = '{}/{}.Semcor{}'.format(output_path_s, corpus_name_s, ending)
c_fn = '{}/{}.COHA{}'.format(output_path_s, corpus_name_s, ending)
s.save(s_fn, pack=True)
c.save(c_fn, pack=True)

lemma='church’
ending = 'socc.cw.tvmx.dist.npy.pac'
s_fn = '{}/{}.{}.Semcor{}'.format(output_path_s, corpus_name_s, lemma, ending)
c_fn = '{}/{}.{}.COHA{}'.format(output_path_s, corpus_name_s, lemma, ending)
s.save(s_fn, pack=True)
c.save(c_fn, pack=True)
```
The first case (for all tokens) works fine, but the second case (random samples and subsets) no .npy file is generated inside the .pac but an .npz file, so not even the TTMatrix.load(s_fn, pack=True) method in the workflow opens it.

**Comment by enzocxt** [comment]
The ending ‘socc.cw.tvmx.dist.npy.pac’ would better be something like ‘socc.cw.ttmx.dist.pac’ or ‘socc.cw.ttmx.dist’ (the code will add ‘.pac’ extension for filename).
And if there is a ‘.npz’ file in ‘.pac’ file, it means that the script may use a SparseMatrix object save() method to save the matrix to file. Therefore there is a ‘.npz’ file that is for a sparse.csr_matrix.
So could you paste the code of creating your s and c?

**Comment by delhikiev** [comment]
This is how I create c when it's for all types:
```python
tokvecs_c = TVMatrix.load('/home/mariana/Python3wf/output/Semcor.cw.COHAsocc.tvmx.pmi', pack=True)
tokvecs_c
[1745, 10000]          be/VBD  be/VBZ  be/VB   have/VBD  not/RB  have/VB  n't/RB  ...
church/NN/br-a01/2073  0.8072  0.9737  0.2617  0.2495    0.1575  0.0365   3.4175  ...
church/NN/br-a07/1303  0.9665  0.0467  0.0000  1.3244    2.7572  0.4424   0.0000  ...
church/NN/br-a07/1325  0.4784  0.3852  2.6692  0.1911    0.5024  1.1725   0.0672  ...
church/NN/br-a07/1487  0.0979  2.2770  1.8454  0.0172    0.3757  0.1934   0.0000  ...
church/NN/br-a10/1754  0.2421  1.6148  1.6454  0.6930    1.1320  1.9523   2.2924  ...
church/NN/br-a10/1769  0.9843  1.7078  1.2087  1.2135    0.7691  0.8485   1.2761  ...
church/NN/br-a10/1850  0.1927  1.0422  0.6692  0.2128    0.1888  0.3759   0.3864  ...
...                    ...     ...     ...     ...       ...     ...      ...     ...
distcosMTX_c = compute_distance(tokvecs_c)
distcosMTX_c.save(c_fn, pack=True)
```
And this is the case for a subset:
```python
church_c = tokvecs_c.select_submatrix('church')
distcosMTX_c = compute_distance(church_c)
distcosMTX_c.save(c_fn, pack=True)
```
with c_fn generated the same way as in the previous post.

**Comment by delhikiev** [comment]
Oh! Sorry! I just realized that I've been doing `church_c.save()` instead of `distcosMTX_c.save()`. That's likely to be the source of the problem!
Will redo it and tell you if it's solved

**Comment by delhikiev** [comment]
Indeed, that was the problem. Sorry I bothered you.

**Comment by enzocxt** [comment]
: -) No problem!
