### ISSUE TITLE
selective subset of token matrix

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#25]
I would like a method where I feed a list of token_ids and can get a token-matrix with those ids.
This is the situation: I have a certain type of data, with many missing values, and would like to generate a distance matrix only for those tokens for which I have the values.

**Comment by enzocxt** [comment]
Hi Mariana,

Have you used the method submatrix of TVMatrix?
I remember that you want select a submatrix of many types which contains only tokens of these types, as following:
    tvmx.submatrix(type_list=a_list_of_types)
Right?

This submatrix also provide parameters row and col.
If you want to select a submatrix of row items (here tokens), use it as:
    tvmx.submatrix(row=token_list)
If you want to select a submatrix of col items (here features), use it as:
    tvmx.submatrix(col=feature_list)

**Comment by delhikiev** [comment]
Excellent, thank you!
`tvmx.submatrix(row=token_list)` is what I needed

**Comment by delhikiev** [comment]
I'm using that method to subset a TVMatrix but the result is a sparse matrix instead of a TVMatrix as well. Why could that be?

![image](https://user-images.githubusercontent.com/16564533/44463480-24b3f700-a618-11e8-9edd-b933c1e4f8ef.png)

**Comment by enzocxt** [comment]
Oh, yes. I know where is the error.
Give me a few minutes.

**Comment by enzocxt** [comment]
I have modified it.
Please try again!

**Comment by delhikiev** [comment]
Solved, thank you!
