### ISSUE TITLE
.drop(n_nonzero =k) removes too many rows

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#28]
I was trying the drop method for the token level matrix. By setting the threshold to 1 (only keep rows that have more than 1 nonzero values), I should keep 244 out of 248 rows, but instead I keep only 20. The count_nonzero() method does identify that there are only 4 tokens with only 1 nonzero value, so there is a discrepancy between them.
Still, count_nonzero() returns row values when axis=1 and column values when it is 0.
![image](https://user-images.githubusercontent.com/16564533/58885923-55ff3e80-86e3-11e9-86fb-12446b18caef.png)

**Comment by enzocxt** [comment]
Yes, you are right. The numpy sum() which `count_zero()` uses has a different way for the meaning of axis=0 or 1. That's the reason why when you drop(axis=0) for rows, the `drop()` uses the result of `count_zero()` for columns.
Now it is fixed. Please check it!

**Comment by delhikiev** [comment]
Checked, it works perfectly, thank you!
