### ISSUE TITLE
IndexError in .drop(axis=1)

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#29]
I understand that I could check which columns have less than k nonzero values by setting the axis parameter to 1 in the .drop() method, but instead we have an IndexError.
![image](https://user-images.githubusercontent.com/16564533/58886099-a080bb00-86e3-11e9-9016-5921f44d6e8c.png)

**Comment by enzocxt** [comment]
Please check it again after I fix the error mentioned in issue 28. This should be the same error raised by the different usage of axis in `count_nonzero()`.

**Comment by delhikiev** [comment]
Yes, solved and checked =)
