### ISSUE TITLE
CollocDict is not defined

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#9]
I have my freqDicts (target_words_name is one of the files), I want to start with the collocation matrix but there is something wrong. Is something else I should be doing first?
```
>>> from typetoken.Manager import ColFreqManager
>>> wordDict = CollocDict.load(target_words_name, encoding=settings['file-encoding'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'CollocDict' is not defined
```

**Comment by enzocxt** [comment]
Just import CollocDict. CollocDict objects are used for the row dict and column dict of all kinds of matrix objects. The rowDict and colDict may have different names in different matrices. For example, wordDict for rowDict and contextDict for colDict of WCMatrix (collocation freq and pmi matrices).
```python
from typetoken.Dict import CollocDict
```
This 'not defined' error may happend often. If you encounter with CollocDict not defined error or with other class name, method name of our model, just import it before use it. If something not exist in our model that occurs in this kind of error. Try to import it as well.
